# Generated by Django 3.1.7 on 2021-05-31 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import quizzify.core.helpers
import quizzify.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.BigIntegerField(default=quizzify.core.helpers.generate_random_id, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('created_by', quizzify.core.models.BigForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_created_by', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(related_name='team', related_query_name='team', to=settings.AUTH_USER_MODEL)),
                ('modified_by', quizzify.core.models.BigForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
