# Generated by Django 3.1.7 on 2021-05-31 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='main_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.team'),
        ),
    ]
