# Generated by Django 3.1.7 on 2021-06-05 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0007_remove_quiz_team'),
        ('users', '0007_user_is_frozen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='team',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='user',
            name='main_team',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
