# Generated by Django 3.1.7 on 2021-06-05 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210605_0701'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='main_team_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
