# Generated by Django 3.1.7 on 2021-06-05 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_main_team_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='scope',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], default='user', max_length=32),
        ),
    ]
