# Generated by Django 3.1.7 on 2021-05-31 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_auto_20210531_0955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='owner',
            new_name='team',
        ),
    ]
