# Generated by Django 3.1.7 on 2021-05-31 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_auto_20210531_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='type',
            field=models.CharField(choices=[('default', 'Default'), ('limited', 'Limited')], default='default', max_length=16),
        ),
    ]
