# Generated by Django 3.1.7 on 2021-06-03 03:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import quizzify.core.helpers
import quizzify.core.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizzes', '0005_quiz_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizItem',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.BigIntegerField(default=quizzify.core.helpers.generate_random_id, primary_key=True, serialize=False)),
                ('order', models.IntegerField()),
                ('question', models.CharField(max_length=256)),
                ('answer', models.TextField(max_length=10000)),
                ('photo', models.ImageField(null=True, upload_to='')),
                ('weight', models.IntegerField(default=1)),
                ('created_by', quizzify.core.models.BigForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizitem_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', quizzify.core.models.BigForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizitem_modified_by', to=settings.AUTH_USER_MODEL)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.quiz')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuizItemAnswer',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.BigIntegerField(default=quizzify.core.helpers.generate_random_id, primary_key=True, serialize=False)),
                ('answer', models.TextField(max_length=10000)),
                ('created_by', quizzify.core.models.BigForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizitemanswer_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', quizzify.core.models.BigForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizitemanswer_modified_by', to=settings.AUTH_USER_MODEL)),
                ('quiz_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.quizitem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemChoice',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.BigIntegerField(default=quizzify.core.helpers.generate_random_id, primary_key=True, serialize=False)),
                ('order', models.IntegerField()),
                ('text', models.CharField(max_length=128)),
                ('created_by', quizzify.core.models.BigForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itemchoice_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', quizzify.core.models.BigForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itemchoice_modified_by', to=settings.AUTH_USER_MODEL)),
                ('quiz_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.quizitem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.BigIntegerField(default=quizzify.core.helpers.generate_random_id, primary_key=True, serialize=False)),
                ('created_by', quizzify.core.models.BigForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', quizzify.core.models.BigForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_modified_by', to=settings.AUTH_USER_MODEL)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.quiz')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
