# Generated by Django 3.1.7 on 2021-06-05 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0006_answer_itemchoice_quizitem_quizitemanswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='team',
        ),
    ]
